### ISSUE TITLE
GitHub Actions causes a segmentation fault while testing and would not stop.

### ISSUE THREAD

**Issue by mtshiba** [erg-lang/erg#188]
**Reproducible code**
```yml
name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose -- --test-threads=2
    - uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings
```
