### ISSUE TITLE
Dict is not implemented

### ISSUE THREAD

**Issue by mtshiba** [erg-lang/erg#35]
Reproducible code:

```
> erg examples/dict.er
```

Result:

```
thread 'main' panicked at 'not yet implemented', C:\Users\sbym8\.cargo\registry\src\github.com-1ecc6299db9ec823\erg_parser-0.2.4\parse.rs:1425:17
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by mtshiba** [comment]
It is not a proper error, but a panic. At least, this needs to be fixed.

**Comment by ShantanuKumar** [comment]
I assume any code level contribution needs Rust proficiency, right?

**Comment by mtshiba** [comment]
Basically, yes. I use advanced and modern features of Rust in several pieces of code.

However, I believe that formatting the code using `cargo fmt` or `clippy`, for example, can be done by someone who is not very familiar with Rust. I have neglected to do this and would be very grateful if you could do it for me.

And I'm planning on making the error messages multilingual. This will be open to anyone who speaks any language other than English.

**Comment by ShantanuKumar** [comment]
> However, I believe that formatting the code using cargo fmt or clippy, for example, can be done by someone who is not very familiar with Rust. I have neglected to do this and would be very grateful if you could do it for me.

Would you like this to be set-up as a pre-commit config? Something like this
```
repos:
  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        description: Check if all files follow the rustfmt style
        entry: cargo fmt --all -- --check --color always
        language: system
        pass_filenames: false
```
